Repository KyoriPowered/adventure-docs, pull requests merged in 2020-11, with the labels that each got.

#10 Some fixes and additions
  source/book.rst
  source/index.rst
  source/migration/text-3.x.rst
Labels: area: api, type: enhancement

#11 Fix title sending tip linking to the wrong method
  source/title.rst
Labels: area: api

#13 Add readme with build instructions
  readme.md
Labels: type: enhancement
