Repository KyoriPowered/adventure-docs, pull requests merged in 2025-04, with the labels that each got.

#208 chore: update velocity support details
  source/platform/native.rst
Labels: type: enhancement, area: api

#204 Write a bit about expectations of platforms
  source/platform/implementing.rst
  source/platform/index.rst
Labels: type: enhancement, area: api, area: base

#205 Localization and MiniMessage translator
  .config/spelling_wordlist.txt
  source/conf.py
  source/contributing.rst
  source/index.rst
  source/localization.rst
  source/minimessage/format.rst
  source/minimessage/index.rst
  source/minimessage/translator.rst
  source/platform/native.rst
Labels: area: api, area: text-minimessage
